version: '3'
services:

    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: DokStoreApp
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    # MySQL Service
    db:
        image: mysql:5.7.33
        platform: linux/amd64
        container_name: DokStoreDatabase
        restart: unless-stopped
        tty: true
        ports:
            - '8889:3306'
        volumes:
            - ./mysql:/var/lib/mysql
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: DokStore
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

    # nginx Service
    webserver:
        image: nginx:alpine
        container_name: DokStoreWeb
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
